//
// Created by andromeda on 3/27/2023.
//

#ifndef STARDUST_ACCELERATIONSTRUCTURERESOURCE_HPP
#define STARDUST_ACCELERATIONSTRUCTURERESOURCE_HPP

#endif //STARDUST_ACCELERATIONSTRUCTURERESOURCE_HPP
